### ISSUE TITLE
hjkl navigation in brackets 1.2

### ISSUE THREAD

**Issue by babydeer** [daveosborne/brackets-vimderbar#37]
Since the update to brackets 1.2 I can no longer hold down ex. "j" to move the cursor down continuously, it simply stops as if I pressed "j" once.

**Comment by daveosborne** [comment]
Hey babydeer, I tried this in Brackets 1.2 in Linux and Windows with version 0.8.0 of the plugin and it works for me when I hold the movement keys. Can you check in the CodeMirror vim demo http://codemirror.net/demo/vim.html and see if it works for you there?

**Comment by babydeer** [comment]
It does not. I tried entering both:
defaults write -g ApplePressAndHoldEnabled -bool true
defaults write -g ApplePressAndHoldEnabled -bool false
into the console, still does not work properly.

**Comment by daveosborne** [comment]
Looks like this is a Mac-specific bug. If it's happening in vanilla CodeMirror, it's outside of anything vimderbar or brackets could be affecting. Does this happen in other apps/browsers? Are all keys not repeating? Does j repeat in insert mode?

I would like to help, but I don't have a Mac to test on. I'm going to close this bug, as the problem lies higher in the dependency tree, but keep me posted if you can isolate it as being a CodeMirror, Chrome or OSX bug.
