### ISSUE TITLE
How to exit insert mode using jj

### ISSUE THREAD

**Issue by polodev** [daveosborne/brackets-vimderbar#42]
I am new in vim. When I am using sublime I can easily change the vim "exit insert mode" keybinding. But I can't  in Adobe Bracket. I would like to use jj shortcut instead of <esc>
:+1: Thanks man for making this awesome plugin. It saves me. I love brackets but lack of vim  plugin I didn't use brackets. Now I am using brackets with assist of your plugin

**Comment by daveosborne** [comment]
I found a way to make this work using CodeMirror's new :imap command `:imap jj <ESC>`, but it doesn't correctly exit insert mode (see codemirror/CodeMirror#3360). We're going to have to wait for a resolution to that issue and wait for the fix to roll into a Brackets release.

I'm working on changing the user key mappings in the preferences file so they are globally applied with the CodeMirror.Vim.map() function, rather than defined as extraKeys options. It will be much easier to define key bindings for any mode.

**Comment by daveosborne** [comment]
Get the latest version of the plugin and put     `"vimderbar.mappings": [{
            "keys": "jj",
            "toKeys": "<Esc>",
            "mode": "insert"
        }]` into your brackets preferences to enable this.

**Comment by takeahot** [comment]
I'm sorry. It isn't working in my case. When I type doubled "j' sings is disappearing but still insert mode.And I also new. May you explain me there I need to see to try correct it by self?

**Comment by takeahot** [comment]
Please, add it advice to readme. I think it will be very useful.

**Comment by mwangaben** [comment]
brackets say "These shortcut are invalid "vimderbar.mappings

**Comment by mwangaben** [comment]
Thanks !###
