### ISSUE TITLE
Incorrect movement in words with scandic characters, like ä and ö

### ISSUE THREAD

**Issue by mkoske** [daveosborne/brackets-vimderbar#45]
Hello,

not sure if this is problem with CodeMirror or what, since the Vim keybindings demo on CodeMirror web site doesn't have this problem.
But, the problem is, when I use `b` and `w` keys to jump over whole words, it stops at the `ä` characters in the word and does not jump over it. 
For example, if I have word `täällä` and I place the cursor in front of that word, I need to type `w` multiple times to get over that word.

**Comment by daveosborne** [comment]
Vimderbar relies on CodeMirror for most of it's vim functionality, CodeMirror has had a number of major updates since Brackets 1.3 was released (with CM 4.11.0).

The one we are interested in here is https://github.com/codemirror/CodeMirror/pull/3108 which fixes the handling of non-ascii chars in words. This was added in CM 5.1.0, so it will definitely be rolled into the next Brackets release.

There are some other great fixes I'm waiting for in Brackets upstream like proper handling of `x` deleting chars, fixing repeat `.` so it will repeat the last macro executed, and handling \r\n\t in substitutions.

I'll leave this open until the upstream candy arrives.

**Comment by daveosborne** [comment]
Fixed in Brackets 1.4
